---

- name: install pkg
  yum: pkg=rsyslog state=installed
  when: rsyslog_install

- name: rsyslog.conf template
  template: 
    src=rsyslog-{{ansible_os_family}}-{{ansible_distribution_major_version}}.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: svc restart rsyslog
  when: ansible_os_family == "RedHat"

- name: rsyslog.d absent
  file:
    dest: "/etc/rsyslog.d/{{item}}.conf"
    state: absent
  with_items: rsyslog_d_absent
  when: ansible_distribution_major_version|int > 5
  notify: svc restart rsyslog

- name: rsyslog.d templates
  template:
    src: "{{item}}.j2"
    dest: "/etc/rsyslog.d/{{item}}"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_d_templates
  when: ansible_distribution_major_version|int > 5
  notify: svc restart rsyslog

- name: rsyslog.d files
  copy:
    src: "{{item.src}}"
    dest: "/etc/rsyslog.d/{{item.name}}"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_d_files
  when: ansible_distribution_major_version|int > 5
  notify: svc restart rsyslog

#- name: rsyslog.d gists
#  get_url:
#    url: "https://gist.githubusercontent.com/{{item.gist}}/raw"
#    dest: "/etc/rsyslog.d/{{ item.dest }}"
#    owner: root
#    group: root
#    mode: 0664
#  with_items: rsyslog_d_gists
#  when: ansible_distribution_major_version|int > 5
#  notify: svc restart rsyslog

- name: create rsyslog.d imfiles
  template:
    src: "rsyslog-imfile.conf.j2"
    dest: "/etc/rsyslog.d/imfile_{{item.name}}.conf"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_imfile
  when: ansible_distribution_major_version|int > 5 and ( item.state is undefined or item.state != "absent" )
  notify: svc restart rsyslog

- name: absent rsyslog.d imfiles
  file:
    dest: "/etc/rsyslog.d/imfile_{{item.name}}.conf"
    state: absent
  with_items: rsyslog_imfile
  when: ansible_distribution_major_version|int > 5 and item.state is defined and item.state == "absent"
  notify: svc restart rsyslog

- name: create rsyslog.d forwarding
  template:
    src: "rsyslog-dest.conf.j2"
    dest: "/etc/rsyslog.d/forwarding_{{item.name}}.conf"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_forwarding
  when: ansible_distribution_major_version|int > 5 and ( item.state is undefined or item.state != "absent" )
  notify: svc restart rsyslog

- name: absent rsyslog.d forwarding
  file:
    dest: "/etc/rsyslog.d/forwarding_{{item.name}}.conf"
  with_items: rsyslog_forwarding
  when: ansible_distribution_major_version|int > 5 and item.state is defined and item.state == "absent"

- name: stop and disable sysklogd
  service:
    name=syslog
    state=stopped
    enabled=no
  when: ansible_distribution_major_version|int == 5 and rsyslog_disable_sysklogd

- name: svc enable, start
  service:
    name=rsyslog
    state={{rsyslog_svc_state}}
    enabled={{rsyslog_svc_enabled}}

