---

- name: install pkg
  yum: pkg=rsyslog state=installed
  when: rsyslog_install

- name: rsyslog.conf template
  template: 
    src=rsyslog-{{ansible_distribution}}-{{ansible_distribution_major_version}}.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644
    backup=yes
  notify: svc restart rsyslog

- name: rsyslog.d absent
  file:
    dest: "/etc/rsyslog.d/{{item}}.conf"
    state: absent
  with_items: rsyslog_d_absent
  when: ansible_distribution_major_version > 5
  notify: svc restart rsyslog

- name: rsyslog.d templates
  template:
    src: "{{item}}.j2"
    dest: "/etc/rsyslog.d/{{item}}"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_d_templates
  when: ansible_distribution_major_version > 5
  notify: svc restart rsyslog

- name: rsyslog.d files
  copy:
    src: "{{item.src}}"
    dest: "/etc/rsyslog.d/{{item.name}}"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_d_files
  when: ansible_distribution_major_version > 5
  notify: svc restart rsyslog

#- name: rsyslog.d gists
#  get_url:
#    url: "https://gist.githubusercontent.com/{{item.gist}}/raw"
#    dest: "/etc/rsyslog.d/{{ item.dest }}"
#    owner: root
#    group: root
#    mode: 0664
#  with_items: rsyslog_d_gists
#  when: ansible_distribution_major_version > 5
#  notify: svc restart rsyslog

- name: rsyslog.d dests
  template:
    src: "rsyslog-dest.conf.j2"
    dest: "/etc/rsyslog.d/rsyslog-{{item.name}}.conf"
    owner: root
    group: root
    mode: 0664
  with_items: rsyslog_dest
  when: ansible_distribution_major_version > 5
  notify: svc restart rsyslog


- name: disable sysklogd
  service:
    name=syslog
    state=stopped
    enabled=no
  when: ansible_distribution_major_version == "5" and rsyslog_disable_sysklogd

- name: svc enable, start
  service:
    name=rsyslog
    state={{rsyslog_svc_state}}
    enabled={{rsyslog_svc_enabled}}

